workflows:
  ios-testflight:
    name: iOS TestFlight Build

    environment:
      flutter: stable

    cache:
      cache_paths:
        - ~/.pub-cache

    scripts:
      - name: Clean project
        script: flutter clean

      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Set build number
        script: |
          BUILD_NUMBER=$(date +%Y%m%d%H%M)
          sed -i '' "s/^version:.*/version: 1.0.0+$BUILD_NUMBER/" pubspec.yaml

      - name: Build iOS IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true