name: bhcfms_app
description: "A secure, clean, and high-performance Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Built-in icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1

  # Network
  dio: ^5.4.3

  # Local Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  # Localization & Fonts
  intl: ^0.20.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
