name: bhcfms_app
description: "A secure, clean, and high-performance Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Built-in icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1

  # Network
  dio: ^5.4.3

  # Local Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  # SVG support
  flutter_svg: ^2.0.10+1

  # Localization & Fonts
  intl: ^0.20.2
  google_fonts: ^6.2.1

  # Charts
  fl_chart: ^0.68.0

  # Image / File Picker
  image_picker: ^1.1.2
  file_picker: ^8.1.2

  # Media Playback
  video_player: ^2.9.2
  just_audio: ^0.9.40

  # PDF Generation & Printing
  pdf: ^3.11.0
  printing: ^5.13.0
  path_provider: ^2.1.0
  share_plus: ^10.0.0

  # Push Notifications (Firebase Cloud Messaging)
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/images/splash/
    - assets/images/auth/
    - assets/letterhead.pdf
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
